### PR TITLE
Add a table of contents for RFCs

### PR DESCRIPTION
**Pull request by alexwlchan**

### CODE REVIEW

**Review by jamesgorrie — COMMENTED** [review]
Given that [gitbook uses the summary doc](https://snowdreams1006.github.io/gitbook-official/en/pages.html), which helps with navigation on https://docs.wellcomecollection.org/developers/ - should we rather use that?

**Comment by jamesgorrie** [comment]
ping @alexwlchan

**Comment by jamesgorrie** [comment]
pong @alexwlchan on this?

**Comment by alexwlchan** [comment]
Urk, I let this languish. Closing this for now as I keep letting it slip.

**Pull request closed without merging**
