### PR TITLE
RFC: Add pipeline tracing

### PR DESCRIPTION
**Pull request by jamieparkinson**
Rendered markdown: https://github.com/wellcomecollection/docs/blob/pipeline-tracing/rfcs/018-pipeline_tracing/README.md

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Good start - could we make it a draft similar to [this](https://github.com/wellcomecollection/docs/tree/pipeline-tracing/rfcs/016-holdings_service#rfc016holdingsservice), then we can merge it in and keep adding.

**Comment by warrd** [comment]
Nice work, looking forward to this making it's way in. Do the RFCs have a set format? I notice other ones have other sections like "Alternatives" etc

**Comment by jamesgorrie** [comment]
> Do the RFCs have a set format?

@warrd 
Yes - looking at past, fully featured ones works well although always up for improving, as you can see if you look at the first ones.

Maybe we could have an RFC for the format of RFCs?

**Comment by jamesgorrie** [comment]
@warrd [things like this do exist](https://github.com/rust-lang/rfcs/blob/master/0000-template.md)

**Comment by jamesgorrie** [comment]
@jamieparkinson it would be good to get some alternatives, and think about any drawbacks to this response.

**Comment by warrd** [comment]
:+1: cheers. Yeah I am aware of the format used for Rust RFCs (and @alexwlchan mentioned they based the idea on that), that's why I thought to ask.

**Comment by jamieparkinson** [comment]
@jamesgorrie @warrd added some thoughts on alternatives and downsides; didn't go the full Rust RFC template route as I think the more specific implementation details will come out in the wash of actually doing this bit of work.

**Comment by kenoir** [comment]
Approach to tracing is sound, opentracing is a good choice. 

Can we provide a specific example of where this would have helped us debug a pipeline issue? 

My impression is that there is a deeper problem identifying **what an error actually is in the applications**. If an error is never flagged up, we will have no mechanism to lead us to a trace.

Some questions I think we need to answer:

- How will this feed into alerting?
- Will this change how we deal with errors in the pipeline now? Will we stop retrying things that throw exceptions, or distinguish between things that need to be retried and things that don't?

**Comment by kenoir** [comment]
> My impression is that there is a deeper problem identifying **what an error actually is in the applications**. If an error is never flagged up, we will have no mechanism to lead us to a trace.

After chatting with @jamieparkinson it is clearer that this will force us to add context to each step in the pipeline that will allow us to pull a set of pipeline events into a thread, thereby enabling more effective debugging.

> - How will this feed into alerting?
> - Will this change how we deal with errors in the pipeline now? Will we stop retrying things that throw exceptions, or distinguish between things that need to be retried and things that don't?

Are questions we should handle separately (not in this RFC).

**Comment by jamieparkinson** [comment]
Merging in anticipation of further PRs on developments

**Pull request merged**
